dist: trusty
sudo: required

language: cpp

matrix:
  include:
    - os: linux
      addons: &gcc7
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=g++-7 BUILD_TYPE=Release STD=17 EXCEPTIONS=ON INT128=ON

    - os: linux
      addons: *gcc7
      env: COMPILER=g++-7 BUILD_TYPE=Debug STD=11 EXCEPTIONS=OFF INT128=OFF

    - os: linux
      addons: &gcc5
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5 BUILD_TYPE=Release STD=14 EXCEPTIONS=ON INT128=ON

    - os: linux
      addons: *gcc5
      env: COMPILER=g++-5 BUILD_TYPE=Release STD=11 EXCEPTIONS=OFF INT128=OFF

    - os: linux
      addons: *gcc5
      env: COMPILER=g++-5 BUILD_TYPE=Debug STD=14 EXCEPTIONS=ON INT128=ON

    - os: linux
      addons: *gcc5
      env: COMPILER=g++-5 BUILD_TYPE=Debug STD=11 EXCEPTIONS=OFF INT128=OFF

    - os: linux
      env: COMPILER=g++ BUILD_TYPE=Debug STD=11 EXCEPTIONS=ON INT128=ON

    - os: linux
      env: COMPILER=g++ BUILD_TYPE=Debug STD=11 EXCEPTIONS=OFF INT128=OFF

    - os: linux
      compiler: clang
      env: COMPILER=clang++ BUILD_TYPE=Release STD=11 EXCEPTIONS=OFF INT128=OFF

    - os: linux
      compiler: clang
      env: COMPILER=clang++ BUILD_TYPE=Debug STD=11 EXCEPTIONS=OFF INT128=OFF

    - os: osx
      compiler: g++
      env: COMPILER=c++ BUILD_TYPE=Release STD=14 EXCEPTIONS=ON INT128=ON

    - os: osx
      compiler: g++
      env: COMPILER=c++ BUILD_TYPE=Debug STD=14 EXCEPTIONS=ON INT128=ON

    - os: osx
      compiler: clang
      env: COMPILER=c++ BUILD_TYPE=Release STD=14 EXCEPTIONS=ON INT128=ON

    - os: osx
      compiler: clang
      env: COMPILER=c++ BUILD_TYPE=Debug STD=14 EXCEPTIONS=ON INT128=ON

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source .travis-setup-linux.sh ; fi

script:
    - export CXX="${COMPILER}"
    - cmake -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DSTD="${STD}" -DEXCEPTIONS="${EXCEPTIONS}" -DINT128="${INT128}"
    - make fp_test fp_benchmark
    - ./fp_test
    - ./fp_benchmark --benchmark_format=csv>result.csv
    - ./src/benchmark/report.py result.csv
    - ls -l fp_benchmark fp_test
